FORMAT: 1A
HOST: https://api.wheniwork.com/2/

# WhenIWork

The When I Work API is thorough, flexible, and restful. Its methods are logically grouped and follow standard conventions. Make a selection from the left to jump to the method group you would like to know more about.

Feel free to contact us if something seems out of place.

## Accounts [/account]

### Listing Accounts [GET]

Listing accounts gives an object with two members: an account object, which specifies the primary account for a given user, and an array, accounts, containing all subaccounts of the primary account.

+ Attributes (Account)

+ Request
    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
        + accounts (array)
            - (Account)
            - (Account)
### Get Existing Account [GET /account/{account_id}]

+ Parameters

    + account_id: 10000 (number, required) - ID of the account to be retrieved.

+ Attributes (Account)

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
### Create Account [POST /account/]

+ Attributes (Account)

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
### Update Account [PUT /account/{account_id}]

+ Parameters

    + account_id: 10000 (number, required) - ID of the account to be retrieved.

+ Attributes (Account)

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
### Claim Account [POST /account/{account_id}/claim]

+ Parameters

    + account_id: 1 (number, required) - ID of the account to be retrieved.

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss

    + Body

            {
                "industry_id": 15,
                "ref_employees": 5-10
            }

+ Response 200 (application/json)

    + Attributes
        + account (Account)
        + user (User)

## Users [/users]
### List Users [GET /users/]

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + users (array)
            - (User)
            - (User)

# Data Structures

## Account (object)

+ id: 10000 (number, required),
+ master_id: 0 (number),
+ country_id: 233 (number),
+ agent_id: 2 (number),
+ type: 3 (number),
+ logo: ''(string),
+ company: ABC Company (string),
+ subdomain: abc-company (string),
+ enabled: true (boolean),
+ custom_domain: ''(string),
+ plan_id: `-1` (number),
- features (array)
    - all
+ wb_expires: false (boolean),
+ plan_custom: 0 (number),
+ plan_texting: false (boolean),
+ text_credits: 25 (number),
+ timezone_id: 11 (number),
+ place_id: 6 (number),
+ place_confirmed: true (boolean),
+ `ref_plan_id`: 0 (number),
+ ref_employees: 3 (number),
+ notifications (array),
+ settings (object)
    - schedule (object)
        - enabled: true (boolean),
        - split_shifts: 0 (number),
        - preferred_hours: true (boolean),
        - shift_acknowledgement: true (boolean),
        - `start_of_week`: 1 (number),
        - 24hour: 0 (number),
        - sort_employees: 0 (number),
        - is_visible: true (boolean),
        - positions_only: false (boolean),
        - open_scheduling: false (boolean),
        - currency: $

   - timeoff (object)
         - enabled: true (boolean),
         - manager_approval: true (boolean),
         - supervisor_autoapprove: true (boolean),
         - days_notice: 0 (number),
         - is_public: true (boolean),
         - `max_hours_per_day`: 8 (number)

   - availability (object)
         - enabled: true (boolean),
         - is_public: true (boolean)

   - swaps (object)
         - enabled: true (boolean),
         - manager_approval: true (boolean)

   - conversations (object)
         - enabled: true (boolean)

   - permissions (object)
        - text_credits: 0 (number)

   - social (object)
        - enabled: true (boolean)

   - privacy (object)
        - enabled: false (boolean)

   - workchat (object)
        - enabled: true (boolean),
        - `last_enabled_date`: null (number)

   - clockin (object)
         - enabled: true (boolean),
         - mobile (object)
               - enabled: true (boolean),
               - strict: false (boolean),
               - radius: 100 (number)
         - work (object)
             - enabled: true (boolean)
         - window: 15 (number)

   - payroll (object)
         - enabled: true (boolean),
         - timesheets: true (boolean),
         - start_date: null (number),
         - type: 0 (number),
         - hours_max: 40 (number),
         - `hours_max_daily`: 24 (number),
         - `hours_dot_daily`: 24 (number),
         - ot_multiplier: 1.5 (number),
         - dbl_multiplier: 2 (number),
         - `work_day_start`: 00:00,
         - adp_enabled: false (boolean),
         - adp_viewable: false (boolean)
   - integrations (object)
         - square: true (boolean),
         - revel: false (boolean)
+ `attendance_alert_manager`: 15,
+ `attendance_alert_employee`: 0,
+ industry_id: 29,
+ referral_id: 0,
+ cancelreason_id: 0,
+ cancelreason_feedback: ,
+ payroll_date: false (boolean),
+ payroll_type: 2,
+ utm_source: ,
+ utm_medium: ,
+ utm_term: ,
+ utm_content: ,
+ utm_campaign: ,
+ is_demo: false (boolean),
+ trial_length: 0,
+ created_at: Mon, 21 Mar 2016 14:08:28 -0500,
+ updated_at: Wed, 13 Apr 2016 17:01:59 -0500,
+ converted_at: false (boolean),
+ is_deactivated: 0,
+ deactivated_at: 0000-00-00 00:00:00,
+ is_deleted: false (boolean),
+ deleted_at: Tue, 29 Nov -001 18:00:00 -0600,
+ `is_default_location_address`: false (boolean),
+ time_format: 0,
+ timezone_name: America/Chicago,
+ `bad_credit_card`: false (boolean),
+ split_shifts: 0,
+ `payroll_overtime_multiplier`: 0,
+ `payroll_hours_max`: 0,
+ uses_features (array)
    - locations,
    - sites
+ required_features: [],
+ limited_features (object)
    - shift_acknowledgement: true (boolean)
+ place (Place)
+ employee_count: 10,
+ user_count: 10,
+ location_count: 3,
+ country (object)
    - id: 233,
    - name: United States,
    - dialing_code: 1,
    - iso3: USA,
    - iso2: US,
    - sms_cost: 0,
    - `sms_credit_cost`: 1,
    - is_deleted: false (boolean)

## Place (object)
- id: 6,
- business_name: Publix Super Market at Cross Creek,
- address: `8360 Charlotte Hwy, Indian Land, SC 29707, United States,`
- latitude: 34.9562318,
- longitude: `-80.8497393`,
- place_type (array)
    - bakery,
    - `grocery_or_supermarket`,
    - liquor_store,
    - store,
    - food,
    - `point_of_interest`,
    - establishment
- place_id: `ChIJjR6Sn8qDVogRKdKpdu-cykM`,
- updated_at: `Wed, 13 Apr 2016 17:01:59 -0500`
## User (object)

+ id: 4364,
+ account_id: 10000,
+ role: 2,
+ email: goldiewilson@hillvalleycalifornia.gov,
+ first_name: Goldie,
+ last_name: Wilson,
+ phone_number: `555-555-5555`,
+ employee_code: 1020,
+ activated: true,
+ notes: ,
+ hours_preferred: 40,
+ hours_max: 40,
+ hourly_rate: 15.5,
+ type: 1,
+ last_login: `Mon, 05 Oct 2015 18:26:44 -0500`,
+ positions (array)
    - 12284,
    - 9554
+ locations (array)
    - 34,
    - 58934
+ is_deleted: false,
+ is_hidden: false,
+ is_payroll: false,
+ is_private: false,
+ is_trusted: false
