### Create Account [POST /account/]

+ Attributes (Account)

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
