### Get Existing Account [GET /account/{account_id}]

+ Parameters

    + account_id: 1 (number, required) - ID of the account to be retrieved.

+ Attributes (Account)

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
