### Claim Account [POST /account/{account_id}/claim]

+ Parameters

    + account_id: 1 (number, required) - ID of the account to be retrieved.

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss

{
    "industry_id": 15,
    "ref_employees": 5-10
}

+ Response 200 (application/json)

    + Attributes
        + account (Account)
        + user (User)
