### Listing Accounts [GET]

Listing accounts gives an object with two members: an account object, which specifies the primary account for a given user, and an array, accounts, containing all subaccounts of the primary account.

+ Attributes (Account)

+ Request
    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + account (Account)
        + accounts (array)
            - (Account)
            - (Account)
