### List Users [GET /users/]

Get a list of users, optionally filtered by ID or location

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss


+ Response 200 (application/json)

    + Attributes
        + users (array)
            - (User)
            - (User)
