### Update User Avatar [POST /users/avatar/{user_id}]

+ Parameters

    + user_id: 4364 (number, required) - ID of the user to be retrieved.

+ Attributes (User)

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss

    + Body (binary)

            {
                "file": avatar.jpg
            }

+ Response 200 (application/json)
