### Update Existing User [PUT /users/{user_id}]

+ Parameters

    + user_id: 4364 (number, required) - ID of the user to be retrieved.

+ Request (application/json)

    + Headers

            W-Token: ilovemyboss

+ Response 200 (application/json)

    + Attributes
        + user (User)
