# WhenIWork

The When I Work API is thorough, flexible, and restful. Its methods are logically grouped and follow standard conventions. Make a selection from the left to jump to the method group you would like to know more about.

Feel free to contact us if something seems out of place.

## Accounts [/account]

:[list](endpoints/accounts/list.apib)
:[find](endpoints/accounts/find.apib)
:[find](endpoints/accounts/create.apib)
:[find](endpoints/accounts/update.apib)

# Data Structures
:[objects](objects.apib)
